### ISSUE TITLE
fudge factor

### ISSUE THREAD

**Issue by y0n1n1** [benbo/adagrad#1]
Hello, I definitely am not a professional at deep learning (unlike you), and I truly appreciate your implementation, it clarified my questions on the matter. I didn't understand why you added the fudge factor outside of the squaring of gti, on a website with the same naming as your implementation (https://ruder.io/optimizing-gradient-descent/#:~:text=In%20its%20update%20rule%2C%20Adagrad,%CF%B5%20%E2%8B%85%20g%20t%20%2C%20i%20.) the author added the fudge factor inside the squaring. Do you know if this matters, if it was your mistake or not and do you have any tips (I am trying to implement adagrad too!).
tysm.

**Comment by benbo** [comment]
The fudge factor is added for numerical stability. It is set to a small value close to zero, e.g. `fudge_factor=1e-6`. Now, imagine `gti` is zero, and `np.sqrt(gti)` will therefore also be zero. If we had no fudge factor, the following would break because we are trying to divide by zero:
`adjusted_grad = grad / (np.sqrt(gti))`

If we instead add the tiny fudge factor, the `adjusted_grad ` would just be divided by a small number and therefore be very large, but not break:
`adjusted_grad = grad / (fudge_factor + np.sqrt(gti))`

Now, you could easily move the fudge factor into the square root, which would also mean that this portion of our code can evaluate
`adjusted_grad = grad / (np.sqrt(fudge_factor + gti))`

They do achieve the same intent here, but we could ask ourselves: what's the difference? It's subtle. `np.sqrt(fudge_factor + 0)` will be greater than `fudge_factor +np.sqrt( 0)` so `adjusted_grad ` won't blow up as much when gti is zero or very close to zero.  At the same time, when gti is very small, having the fudge inside the square operation dilutes the impact the small gti value has on `adjusted_grad`. Maybe you would not want that to be the case, but instead you might in fact want the `adjusted_grad ` to be very large. I'm honestly not sure how much it would matter in practice and if one approach for adding the fudge factor could be superior to the other. I hope this explanation helps.

**Comment by y0n1n1** [comment]
Thank you for explaining, since it already is so small there isn't much difference on where to put it.
